import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SessionProviderWrapper } from "@/components/SessionProviderWrapper";
import { Toaster } from "@/components/ui/sonner"
export const metadata: Metadata = {
  title: "Biowave",
  description: "Generated by create next app",
};

const kohinoor = localFont({
  src: [
    {
      path: "../public/fonts/Kohinoor.Arabic.Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Kohinoor.Arabic.Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Kohinoor.Arabic.Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Kohinoor.Arabic.Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/Kohinoor.Arabic.Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-kohinoor",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
            <SessionProviderWrapper>

    <html lang="fa" className={kohinoor.variable}>
      <body className="antialiased">{children}
                <Toaster /> 
      </body>
    </html>
            </SessionProviderWrapper>

  );
}
